# Generated by Django 2.2.16 on 2023-04-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230419_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Сообщение',), 'verbose_name_plural': ('Сообщения',)},
        ),
    ]
