# Generated by Django 2.2.16 on 2023-04-26 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20230424_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст сообщения', verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата публикации комментария', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Напишите комментарий', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментарий')),
                ('post', models.ForeignKey(help_text='Напишите комментарий к сообщению', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Комментарий к сообщению')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
